apps:
  tooljet:
    service:
      type: NodePort
      host: "http://localhost"
    deployment:
      image:
        repository: tooljet/tooljet-ce
        pullPolicy: Always
        tag: v2.14.0
      resources:
        requests:
          memory: "300Mi"
          cpu: "300m"
        limits:
          memory: "500Mi"
          cpu: "500m"
    hpa:
      min: 1
      max: 1
      threshhold:
        cpu: 0.75
        ram: 768Mi
    secret:
      name: tooljet-server
      data:
        lockbox_key: "0123456789ABCDEF"
        secret_key_base: "0123456789ABCDEF"

ingress:
  enabled: true
  ingressClassName: alb
  kubernetes.io/ingress.class: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  tls: []
# https://artifacthub.io/packages/helm/bitnami/postgresql#global-parameters

# https://artifacthub.io/packages/helm/bitnami/postgresql#global-parameters
postgresql:
  enabled: true
  postgresqlExtendedConf:
    maxConnections: 1024
  replication:
    enabled: true
  auth:
    username: "postgres"
    # Keys below are ignored if auth.existingSecret with key password is provided
    postgresPassword: "postgres" # Password for the "postgres" admin user
    password: "postgres"
    database: "tooljet_production"
  primary:
    persistence:
      enabled: true
      size: 500Mi
      storageClass: ""
  # The following variables are to be used when internal PG is disabled
  # postgresqlHost: postgres
  # postgresqlPort: 5432
  # When defined the `postgresqlPassword` field is ignored
  # existingSecret: secret-name
  # existingSecretKey: password

# Environment variables
# Configure additional env variables down below
# https://docs.tooljet.com/docs/setup/env-vars/
env:
  DEPLOYMENT_PLATFORM: "k8s:helm"
  db_uri: "postgres://postgres:postgres@tooljet-postgresql.default.svc.cluster.local:5432/tooljet_db"
  jwt_secret: "779ce303294a7d84a2aea9ff1ef1912f9ac57220a0dd2c0861a11ca5ae6c5817"
  ENABLE_TOOLJET_DB: '"false"'
  TOOLJET_DB_USER: "postgres"
  TOOLJET_DB_HOST: "tooljet-postgresql"
  TOOLJET_DB_PASS: "postgres"
  TOOLJET_DB: "tooljet_db"
  PGRST_HOST: "tooljet-postgrest.default.svc.cluster.local"

enterprise:
  enabled: false
  LICENSE_KEY: ""
  REDIS_HOST: "redis-master"
  REDIS_PORT: '"6379"'

redis:
  fullnameOverride: redis
  usePassword: false
  auth:
    enabled: false  

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

image:
  repository: postgrest/postgrest
  tag: v10.2.0
  pullPolicy: IfNotPresent

postgrest:
  targetPort: 3000
  port: 80
  containerPort: 3000

replicaCount: 1
nodeSelector:
  nodegroup: ng-service-x86_64